# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Semester.create(title: "Jan-May 2014")
Semester.create(title: "Aug-Dec 2014")
Semester.create(title: "Jan-May 2015")
Semester.create(title: "Aug-Dec 2015")
Semester.create(title: "Jan-May 2016")
Semester.create(title: "Aug-Dec 2016")

m = Topic.create(name: "Math")
cs = Topic.create(name: "Computer Science")
h = Topic.create(name: "Mexican History")
f = Topic.create(name: "Physics")
q = Topic.create(name: "Chemistry")
b = Topic.create(name: "Biology")
k = Topic.create(name: "Kindergarten")
n = Topic.create(name: "Christmas")

a = Category.create(name: "Algebra", topic: m)
Clue.create(title: "Clue 1", points: 500, category: a, question: "Yes")
Clue.create(title: "Clue 2", points: 400, category: a, question: "Yes")
Clue.create(title: "Clue 3", points: 300, category: a, question: "Yes")
Clue.create(title: "Clue 4", points: 200, category: a, question: "Yes")
Clue.create(title: "Clue 5", points: 100, category: a, question: "Yes")

a = Category.create(name: "Simple Math", topic: m)
Clue.create(title: "Clue 1", points: 500, category: a, question: "Yes")
Clue.create(title: "Clue 2", points: 400, category: a, question: "Yes")
Clue.create(title: "Clue 3", points: 300, category: a, question: "Yes")
Clue.create(title: "Clue 4", points: 200, category: a, question: "Yes")
Clue.create(title: "Clue 5", points: 100, category: a, question: "Yes")

a = Category.create(name: "Calculus", topic: m)
Clue.create(title: "Clue 1", points: 500, category: a, question: "Yes")
Clue.create(title: "Clue 2", points: 400, category: a, question: "Yes")
Clue.create(title: "Clue 3", points: 300, category: a, question: "Yes")
Clue.create(title: "Clue 4", points: 200, category: a, question: "Yes")
Clue.create(title: "Clue 5", points: 100, category: a, question: "Yes")

a = Category.create(name: "Trigonometry", topic: m)
Clue.create(title: "Clue 1", points: 500, category: a, question: "Yes")
Clue.create(title: "Clue 2", points: 400, category: a, question: "Yes")
Clue.create(title: "Clue 3", points: 300, category: a, question: "Yes")
Clue.create(title: "Clue 4", points: 200, category: a, question: "Yes")
Clue.create(title: "Clue 5", points: 100, category: a, question: "Yes")

a = Category.create(name: "Networks", topic: cs)
Clue.create(title: "Clue 1", points: 500, category: a, question: "Yes")
Clue.create(title: "Clue 2", points: 400, category: a, question: "Yes")
Clue.create(title: "Clue 3", points: 300, category: a, question: "Yes")
Clue.create(title: "Clue 4", points: 200, category: a, question: "Yes")
Clue.create(title: "Clue 5", points: 100, category: a, question: "Yes")

a = Category.create(name: "Algorithms", topic: cs)
Clue.create(title: "Clue 1", points: 500, category: a, question: "Yes")
Clue.create(title: "Clue 2", points: 400, category: a, question: "Yes")
Clue.create(title: "Clue 3", points: 300, category: a, question: "Yes")
Clue.create(title: "Clue 4", points: 200, category: a, question: "Yes")
Clue.create(title: "Clue 5", points: 100, category: a, question: "Yes")

a = Category.create(name: "Databases", topic: cs)
Clue.create(title: "Clue 1", points: 500, category: a, question: "Yes")
Clue.create(title: "Clue 2", points: 400, category: a, question: "Yes")
Clue.create(title: "Clue 3", points: 300, category: a, question: "Yes")
Clue.create(title: "Clue 4", points: 200, category: a, question: "Yes")
Clue.create(title: "Clue 5", points: 100, category: a, question: "Yes")

a = Category.create(name: "Operating Systems", topic: cs)
Clue.create(title: "Clue 1", points: 500, category: a, question: "Yes")
Clue.create(title: "Clue 2", points: 400, category: a, question: "Yes")
Clue.create(title: "Clue 3", points: 300, category: a, question: "Yes")
Clue.create(title: "Clue 4", points: 200, category: a, question: "Yes")
Clue.create(title: "Clue 5", points: 100, category: a, question: "Yes")

a = Category.create(name: "People", topic: h)
Clue.create(title: "Clue 1", points: 500, category: a, question: "Yes")
Clue.create(title: "Clue 2", points: 400, category: a, question: "Yes")
Clue.create(title: "Clue 3", points: 300, category: a, question: "Yes")
Clue.create(title: "Clue 4", points: 200, category: a, question: "Yes")
Clue.create(title: "Clue 5", points: 100, category: a, question: "Yes")

a = Category.create(name: "Dates", topic: h)
Clue.create(title: "Clue 1", points: 500, category: a, question: "Yes")
Clue.create(title: "Clue 2", points: 400, category: a, question: "Yes")
Clue.create(title: "Clue 3", points: 300, category: a, question: "Yes")
Clue.create(title: "Clue 4", points: 200, category: a, question: "Yes")
Clue.create(title: "Clue 5", points: 100, category: a, question: "Yes")

a = Category.create(name: "Fun Facts", topic: h)
Clue.create(title: "Clue 1", points: 500, category: a, question: "Yes")
Clue.create(title: "Clue 2", points: 400, category: a, question: "Yes")
Clue.create(title: "Clue 3", points: 300, category: a, question: "Yes")
Clue.create(title: "Clue 4", points: 200, category: a, question: "Yes")
Clue.create(title: "Clue 5", points: 100, category: a, question: "Yes")

a = Category.create(name: "Pre Hispanic", topic: h)
Clue.create(title: "Clue 1", points: 500, category: a, question: "Yes")
Clue.create(title: "Clue 2", points: 400, category: a, question: "Yes")
Clue.create(title: "Clue 3", points: 300, category: a, question: "Yes")
Clue.create(title: "Clue 4", points: 200, category: a, question: "Yes")
Clue.create(title: "Clue 5", points: 100, category: a, question: "Yes")

a = Category.create(name: "Relativity", topic: f)
Clue.create(title: "Clue 1", points: 500, category: a, question: "Yes")
Clue.create(title: "Clue 2", points: 400, category: a, question: "Yes")
Clue.create(title: "Clue 3", points: 300, category: a, question: "Yes")
Clue.create(title: "Clue 4", points: 200, category: a, question: "Yes")
Clue.create(title: "Clue 5", points: 100, category: a, question: "Yes")

a = Category.create(name: "Elementary Physics", topic: f)
Clue.create(title: "Clue 1", points: 500, category: a, question: "Yes")
Clue.create(title: "Clue 2", points: 400, category: a, question: "Yes")
Clue.create(title: "Clue 3", points: 300, category: a, question: "Yes")
Clue.create(title: "Clue 4", points: 200, category: a, question: "Yes")
Clue.create(title: "Clue 5", points: 100, category: a, question: "Yes")

a = Category.create(name: "Quantum Physics", topic: f)
Clue.create(title: "Clue 1", points: 500, category: a, question: "Yes")
Clue.create(title: "Clue 2", points: 400, category: a, question: "Yes")
Clue.create(title: "Clue 3", points: 300, category: a, question: "Yes")
Clue.create(title: "Clue 4", points: 200, category: a, question: "Yes")
Clue.create(title: "Clue 5", points: 100, category: a, question: "Yes")

a = Category.create(name: "Weird Stuff", topic: f)
Clue.create(title: "Clue 1", points: 500, category: a, question: "Yes")
Clue.create(title: "Clue 2", points: 400, category: a, question: "Yes")
Clue.create(title: "Clue 3", points: 300, category: a, question: "Yes")
Clue.create(title: "Clue 4", points: 200, category: a, question: "Yes")
Clue.create(title: "Clue 5", points: 100, category: a, question: "Yes")

a = Category.create(name: "Reactions", topic: q)
Clue.create(title: "Clue 1", points: 500, category: a, question: "Yes")
Clue.create(title: "Clue 2", points: 400, category: a, question: "Yes")
Clue.create(title: "Clue 3", points: 300, category: a, question: "Yes")
Clue.create(title: "Clue 4", points: 200, category: a, question: "Yes")
Clue.create(title: "Clue 5", points: 100, category: a, question: "Yes")

a = Category.create(name: "Formulas", topic: q)
Clue.create(title: "Clue 1", points: 500, category: a, question: "Yes")
Clue.create(title: "Clue 2", points: 400, category: a, question: "Yes")
Clue.create(title: "Clue 3", points: 300, category: a, question: "Yes")
Clue.create(title: "Clue 4", points: 200, category: a, question: "Yes")
Clue.create(title: "Clue 5", points: 100, category: a, question: "Yes")

a = Category.create(name: "Periodic Table", topic: q)
Clue.create(title: "Clue 1", points: 500, category: a, question: "Yes")
Clue.create(title: "Clue 2", points: 400, category: a, question: "Yes")
Clue.create(title: "Clue 3", points: 300, category: a, question: "Yes")
Clue.create(title: "Clue 4", points: 200, category: a, question: "Yes")
Clue.create(title: "Clue 5", points: 100, category: a, question: "Yes")

a = Category.create(name: "Ions", topic: q)
Clue.create(title: "Clue 1", points: 500, category: a, question: "Yes")
Clue.create(title: "Clue 2", points: 400, category: a, question: "Yes")
Clue.create(title: "Clue 3", points: 300, category: a, question: "Yes")
Clue.create(title: "Clue 4", points: 200, category: a, question: "Yes")
Clue.create(title: "Clue 5", points: 100, category: a, question: "Yes")

a = Category.create(name: "Plants", topic: b)
Clue.create(title: "Clue 1", points: 500, category: a, question: "Yes")
Clue.create(title: "Clue 2", points: 400, category: a, question: "Yes")
Clue.create(title: "Clue 3", points: 300, category: a, question: "Yes")
Clue.create(title: "Clue 4", points: 200, category: a, question: "Yes")
Clue.create(title: "Clue 5", points: 100, category: a, question: "Yes")

a = Category.create(name: "Processes", topic: b)
Clue.create(title: "Clue 1", points: 500, category: a, question: "Yes")
Clue.create(title: "Clue 2", points: 400, category: a, question: "Yes")
Clue.create(title: "Clue 3", points: 300, category: a, question: "Yes")
Clue.create(title: "Clue 4", points: 200, category: a, question: "Yes")
Clue.create(title: "Clue 5", points: 100, category: a, question: "Yes")

a = Category.create(name: "Something", topic: b)
Clue.create(title: "Clue 1", points: 500, category: a, question: "Yes")
Clue.create(title: "Clue 2", points: 400, category: a, question: "Yes")
Clue.create(title: "Clue 3", points: 300, category: a, question: "Yes")
Clue.create(title: "Clue 4", points: 200, category: a, question: "Yes")
Clue.create(title: "Clue 5", points: 100, category: a, question: "Yes")

a = Category.create(name: "Food", topic: b)
Clue.create(title: "Clue 1", points: 500, category: a, question: "Yes")
Clue.create(title: "Clue 2", points: 400, category: a, question: "Yes")
Clue.create(title: "Clue 3", points: 300, category: a, question: "Yes")
Clue.create(title: "Clue 4", points: 200, category: a, question: "Yes")
Clue.create(title: "Clue 5", points: 100, category: a, question: "Yes")

a = Category.create(name: "Shapes", topic: k)
Clue.create(title: "Two triangles can make a:", points: 500, category: a, question:"Square/Rectangle")
Clue.create(title: "Shape of the sun", points: 400, category: a, question: "Sphere")
Clue.create(title: "Shape of your bed", points: 300, category: a, question: "Rectangle")
Clue.create(title: "Shape of a pyramid", points: 200, category: a, question: "Triangle")
Clue.create(title: "4 equal lines can make a", points: 100, category: a, question: "Square")

a = Category.create(name: "Numbers", topic: k)
Clue.create(title: "Clue 1", points: 500, category: a, question: "Yes")
Clue.create(title: "Clue 2", points: 400, category: a, question: "Yes")
Clue.create(title: "Clue 3", points: 300, category: a, question: "Yes")
Clue.create(title: "Clue 4", points: 200, category: a, question: "Yes")
Clue.create(title: "Clue 5", points: 100, category: a, question: "Yes")

a = Category.create(name: "Colors", topic: k)
Clue.create(title: "Black + white = ", points: 500, category: a, question: "Gray")
Clue.create(title: "Red + Blue = ", points: 400, category: a, question: "Purple")
Clue.create(title: "The three primary colors:", points: 300, category: a, question: "Red, yellow, blue")
Clue.create(title: "Color the sky", points: 200, category: a, question: "Blue")
Clue.create(title: "Fruit and color share same name", points: 100, category: a, question: "Orange")

a = Category.create(name: "Tools", topic: k)
Clue.create(title: "Clue 1", points: 500, category: a, question: "Yes")
Clue.create(title: "Clue 2", points: 400, category: a, question: "Yes")
Clue.create(title: "Clue 3", points: 300, category: a, question: "Yes")
Clue.create(title: "Clue 4", points: 200, category: a, question: "Yes")
Clue.create(title: "Clue 5", points: 100, category: a, question: "Yes")

a = Category.create(name: "Dates", topic: n)
Clue.create(title: "Clue 1", points: 500, category: a, question: "Yes")
Clue.create(title: "Clue 2", points: 400, category: a, question: "Yes")
Clue.create(title: "Clue 3", points: 300, category: a, question: "Yes")
Clue.create(title: "Clue 4", points: 200, category: a, question: "Yes")
Clue.create(title: "Clue 5", points: 100, category: a, question: "Yes")

a = Category.create(name: "Presents", topic: n)
Clue.create(title: "Clue 1", points: 500, category: a, question: "Yes")
Clue.create(title: "Clue 2", points: 400, category: a, question: "Yes")
Clue.create(title: "Clue 3", points: 300, category: a, question: "Yes")
Clue.create(title: "Clue 4", points: 200, category: a, question: "Yes")
Clue.create(title: "Clue 5", points: 100, category: a, question: "Yes")

a = Category.create(name: "Happiness", topic: n)
Clue.create(title: "Clue 1", points: 500, category: a, question: "Yes")
Clue.create(title: "Clue 2", points: 400, category: a, question: "Yes")
Clue.create(title: "Clue 3", points: 300, category: a, question: "Yes")
Clue.create(title: "Clue 4", points: 200, category: a, question: "Yes")
Clue.create(title: "Clue 5", points: 100, category: a, question: "Yes")

a = Category.create(name: "Characters", topic: n)
Clue.create(title: "Clue 1", points: 500, category: a, question: "Yes")
Clue.create(title: "Clue 2", points: 400, category: a, question: "Yes")
Clue.create(title: "Clue 3", points: 300, category: a, question: "Yes")
Clue.create(title: "Clue 4", points: 200, category: a, question: "Yes")
Clue.create(title: "Clue 5", points: 100, category: a, question: "Yes")

